language: csharp
solution: TorrentClient.sln
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
      script:
        - dotnet build
    - mono: latest
      script:
        - xbuild /p:Configuration=Release TorrentClient.sln
  